# Generated by Django 6.0.2 on 2026-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='biometriccredential',
            name='face_vector_1',
        ),
        migrations.RemoveField(
            model_name='biometriccredential',
            name='face_vector_2',
        ),
        migrations.AddField(
            model_name='biometriccredential',
            name='face_embeddings',
            field=models.JSONField(blank=True, default=list, help_text='\n        Danh sách các vector khuôn mặt. Định dạng chuẩn:\n        [\n            {"type": "primary", "vector": [0.12, -0.45, ...]},\n            {"type": "with_glasses", "vector": [0.11, -0.42, ...]},\n            {"type": "left_side", "vector": [0.08, -0.50, ...]}\n        ]\n        '),
        ),
    ]
