# Generated by Django 6.0.2 on 2026-03-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0002_rename_dob_profile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biometriccredential",
            name="face_embeddings",
        ),
    ]
