# Generated by Django 6.0.2 on 2026-03-17 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0003_remove_biometriccredential_face_embeddings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=50)),
                ("template_type", models.CharField(default="primary", max_length=30)),
                ("vector", models.JSONField()),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True, help_text="Điểm chất lượng của ảnh gốc", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "biometric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_templates",
                        to="custom_account.biometriccredential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Template",
                "unique_together": {("biometric", "model_name", "template_type")},
            },
        ),
    ]
