# Generated by Django 6.0.2 on 2026-03-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0004_facetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="identity_code",
            field=models.CharField(
                blank=True,
                help_text="Mã định danh vật lý (VD: HS0001, GV0002). Dùng làm tên folder ảnh.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
