# Generated by Django 6.0.2 on 2026-03-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0005_profile_identity_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="student_code",
        ),
    ]
