# Generated by Django 6.0.2 on 2026-03-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0006_remove_studentprofile_student_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="enrollment_year",
            field=models.IntegerField(default=2026, help_text="Năm nhập học"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_name",
            field=models.CharField(
                blank=True, help_text="Tên phụ huynh", max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="parent_phone",
            field=models.CharField(
                blank=True,
                help_text="Số điện thoại phụ huynh để báo điểm danh",
                max_length=15,
                null=True,
            ),
        ),
    ]
