# Generated by Django 6.0.2 on 2026-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0007_studentprofile_enrollment_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="enrollment_year",
            field=models.IntegerField(default=0, help_text="Năm nhập học"),
        ),
    ]
