# Generated by Django 6.0.3 on 2026-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0008_alter_studentprofile_enrollment_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facetemplate',
            name='quality_score',
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='intra_sim_score',
            field=models.FloatField(blank=True, help_text='Độ đồng nhất của các ảnh gốc', null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Tắt đi nếu template này hay gây nhận vơ'),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='sample_count',
            field=models.PositiveIntegerField(default=1, help_text='Số ảnh tạo nên vector này'),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='soft_margin',
            field=models.FloatField(blank=True, help_text='Độ an toàn cá nhân lúc khởi tạo', null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='source',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
