# Generated by Django 6.0.3 on 2026-03-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0009_remove_facetemplate_quality_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='identity_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
