# Generated by Django 6.0.3 on 2026-03-27 12:43

from django.db import migrations

def move_identity_code(apps, schema_editor):
    # Lấy model thông qua apps.get_model thay vì import trực tiếp
    UserModel = apps.get_model('custom_account', 'UserModel')
    Profile = apps.get_model('custom_account', 'Profile')

    # Lọc các profile có data
    profiles = Profile.objects.exclude(
        identity_code__isnull=True
    ).exclude(
        identity_code__exact=''
    ).select_related('user')

    users_to_update = []
    for profile in profiles:
        user = profile.user
        user.identity_code = profile.identity_code
        users_to_update.append(user)

    # Đẩy xuống DB bằng 1 query
    if users_to_update:
        UserModel.objects.bulk_update(users_to_update, ['identity_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0010_usermodel_identity_code'),
    ]

    operations = [
        migrations.RunPython(move_identity_code),
    ]
