# Generated by Django 6.0.3 on 2026-03-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0011_auto_20260327_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='identity_code',
        ),
    ]
