# Generated by Django 6.0.3 on 2026-03-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0012_remove_profile_identity_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='identity_code',
            field=models.CharField(blank=True, help_text='Mã định danh vật lý (VD: HS0001, GV0002). Dùng làm tên folder ảnh.', max_length=50, null=True, unique=True),
        ),
    ]
