# Generated by Django 6.0.3 on 2026-03-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_account", "0013_alter_usermodel_identity_code"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="facetemplate",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="facetemplate",
            name="biometric",
        ),
        migrations.DeleteModel(
            name="BiometricCredential",
        ),
        migrations.DeleteModel(
            name="FaceTemplate",
        ),
    ]
