# Generated by Django 6.0.2 on 2026-03-11 01:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(help_text='Mã thiết bị điểm danh (VD: GATE_01_GATEWAY)', max_length=100)),
                ('check_in_time', models.DateTimeField(db_index=True)),
                ('method', models.CharField(choices=[('face', 'Khuôn mặt'), ('rfid', 'Thẻ từ / RFID'), ('qr', 'Mã QR'), ('manual', 'Thủ công (Giáo viên thêm)')], default='face', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Độ tự tin của AI khi nhận diện (VD: 0.98 là 98% giống)', null=True)),
                ('is_offline_log', models.BooleanField(default=False, help_text='True nếu điểm danh lúc rớt mạng và được đồng bộ đẩy lên sau')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử điểm danh',
                'verbose_name_plural': 'Lịch sử điểm danh',
                'ordering': ['-check_in_time'],
                'indexes': [models.Index(fields=['user', 'check_in_time'], name='offline_syn_user_id_1fdec4_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'check_in_time'), name='unique_attendance_per_user_time')],
            },
        ),
    ]
