# Generated by Django 6.0.2 on 2026-03-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offline_sync", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="evidence_image",
            field=models.ImageField(
                blank=True,
                help_text="Ảnh chụp lại khuôn mặt lúc điểm danh để đối chứng",
                null=True,
                upload_to="attendance_evidence/%Y-%m-%d/",
            ),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="liveness_score",
            field=models.FloatField(
                blank=True,
                help_text="Điểm chống giả mạo (Spoofing) (VD: 0.99 là người thật)",
                null=True,
            ),
        ),
    ]
