# Generated by Django 6.0.3 on 2026-03-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_account', '0013_alter_usermodel_identity_code'),
        ('offline_sync', '0002_attendancelog_evidence_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricCredential',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='new_biometric', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rfid_card_id', models.CharField(blank=True, help_text='Mã thẻ cứng RFID', max_length=50, null=True, unique=True)),
                ('qr_code_secret', models.CharField(blank=True, help_text='Mã bí mật tạo QR động', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Khóa thẻ/mặt nếu báo mất')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=50)),
                ('template_type', models.CharField(default='primary', max_length=30)),
                ('vector', models.JSONField()),
                ('is_active', models.BooleanField(default=True, help_text='Tắt đi nếu template này hay gây nhận vơ')),
                ('sample_count', models.PositiveIntegerField(default=1, help_text='Số ảnh tạo nên vector này')),
                ('intra_sim_score', models.FloatField(blank=True, help_text='Độ đồng nhất của các ảnh gốc', null=True)),
                ('soft_margin', models.FloatField(blank=True, help_text='Độ an toàn cá nhân lúc khởi tạo', null=True)),
                ('source', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('biometric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_face_templates', to='offline_sync.biometriccredential')),
            ],
            options={
                'verbose_name': 'Face Template',
                'unique_together': {('biometric', 'model_name', 'template_type')},
            },
        ),
    ]
