# Generated by Django 6.0.3 on 2026-03-27 13:10

from django.db import migrations


def copy_biometric_data(apps, schema_editor):
    # Lấy models từ cả 2 app
    OldBiometric = apps.get_model("custom_account", "BiometricCredential")
    NewBiometric = apps.get_model("offline_sync", "BiometricCredential")

    OldFaceTemplate = apps.get_model("custom_account", "FaceTemplate")
    NewFaceTemplate = apps.get_model("offline_sync", "FaceTemplate")

    # 1. Copy dữ liệu BiometricCredential trước (vì FaceTemplate phụ thuộc vào nó)
    new_bios = []
    for old_bio in OldBiometric.objects.all():
        new_bios.append(
            NewBiometric(
                user_id=old_bio.user_id,  # PK là user_id
                rfid_card_id=old_bio.rfid_card_id,
                qr_code_secret=old_bio.qr_code_secret,
                is_active=old_bio.is_active,
                updated_at=old_bio.updated_at,
            )
        )
    if new_bios:
        NewBiometric.objects.bulk_create(new_bios)

    # 2. Copy dữ liệu FaceTemplate
    new_faces = []
    for old_face in OldFaceTemplate.objects.all():
        new_faces.append(
            NewFaceTemplate(
                id=old_face.id,  # Giữ nguyên ID cũ
                biometric_id=old_face.biometric_id,  # Khóa ngoại trỏ về user_id
                model_name=old_face.model_name,
                template_type=old_face.template_type,
                vector=old_face.vector,
                is_active=old_face.is_active,
                sample_count=old_face.sample_count,
                intra_sim_score=old_face.intra_sim_score,
                soft_margin=old_face.soft_margin,
                source=old_face.source,
                created_at=old_face.created_at,
                last_used_at=old_face.last_used_at,
            )
        )
    if new_faces:
        NewFaceTemplate.objects.bulk_create(new_faces)


class Migration(migrations.Migration):

    dependencies = [
        ("offline_sync", "0003_biometriccredential_facetemplate"),
        ("custom_account", "0013_alter_usermodel_identity_code"),
    ]

    operations = [
        migrations.RunPython(copy_biometric_data),
    ]
