# Generated by Django 6.0.3 on 2026-03-27 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0004_auto_20260327_2010'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometriccredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='biometric', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facetemplate',
            name='biometric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_templates', to='offline_sync.biometriccredential'),
        ),
    ]
