# Generated by Django 6.0.3 on 2026-03-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0005_alter_biometriccredential_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facetemplate',
            unique_together={('biometric', 'template_type')},
        ),
        migrations.RemoveField(
            model_name='facetemplate',
            name='model_name',
        ),
    ]
