# Generated by Django 6.0.3 on 2026-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0006_alter_facetemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facetemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='detector_model',
            field=models.CharField(blank=True, default='unknown', help_text='Model cắt mặt (VD: retinaface, scrfd)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='extractor_model',
            field=models.CharField(blank=True, db_index=True, help_text='Model tạo vector (VD: mobilefacenet, arcface_r100)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='vector_dimension',
            field=models.PositiveIntegerField(default=0, help_text='Kích thước vector (128, 512...)'),
        ),
        migrations.AlterUniqueTogether(
            name='facetemplate',
            unique_together={('biometric', 'detector_model', 'extractor_model', 'template_type')},
        ),
    ]
