# Generated by Django 6.0.3 on 2026-03-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0007_alter_facetemplate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetemplate',
            name='face_quality_score',
            field=models.FloatField(blank=True, help_text='Điểm đánh giá chất lượng ảnh lúc đăng ký (độ sáng, rõ nét)', null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='image_ref',
            field=models.CharField(blank=True, help_text='Đường dẫn tới ảnh gốc đã crop để debug AI', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facetemplate',
            name='vector',
            field=models.JSONField(help_text='Mảng float đặc trưng'),
        ),
    ]
