# Generated by Django 6.0.3 on 2026-03-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0008_facetemplate_face_quality_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facetemplate',
            name='vector',
        ),
    ]
