# Generated by Django 6.0.3 on 2026-03-27 14:25

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0009_remove_facetemplate_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetemplate',
            name='vector_128',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=128, help_text='Trường vector 128 chiều', null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='vector_512',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, help_text='Trường vector 512 chiều', null=True),
        ),
        migrations.AddField(
            model_name='facetemplate',
            name='vector_json',
            field=models.JSONField(default=list, help_text='Mảng float lưu dạng JSON cho offline sync'),
        ),
    ]
