# Generated by Django 6.0.3 on 2026-03-27 14:36

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0010_facetemplate_vector_128_facetemplate_vector_512_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='facetemplate',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector_128'], m=16, name='hnsw_128_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='facetemplate',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector_512'], m=16, name='hnsw_512_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
