# Generated by Django 6.0.3 on 2026-03-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0011_facetemplate_hnsw_128_idx_facetemplate_hnsw_512_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_image', models.ImageField(help_text='Ảnh gốc lúc đăng ký', upload_to='enrollment_raw_samples/%Y/%m/')),
                ('vector_json', models.JSONField(blank=True, help_text='Vector đơn lẻ của bức ảnh này', null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_best_shot', models.BooleanField(default=False, help_text='Đánh dấu đây có phải bức ảnh đẹp nhất để làm image_ref không')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_samples', to='offline_sync.facetemplate')),
            ],
            options={
                'verbose_name': 'Raw Enrollment Sample',
            },
        ),
    ]
