# Generated by Django 6.0.3 on 2026-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0012_enrollmentsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetemplate',
            name='quality_assessor',
            field=models.CharField(blank=True, default='unknown', help_text='Model chấm điểm chất lượng (VD: lightqnet, opencv_math)', max_length=50, null=True),
        ),
    ]
