# Generated by Django 6.0.3 on 2026-04-01 04:01

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_sync', '0013_facetemplate_quality_assessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetemplate',
            name='vector_192',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=192, help_text='Dành cho 192 chiều', null=True),
        ),
        migrations.AddIndex(
            model_name='facetemplate',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector_192'], m=16, name='hnsw_192_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
